baseURL = "http://my-hugo-demo.s3-website.eu-central-1.amazonaws.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hyde"

[deployment]

[[deployment.targets]]
name = "mydeployment"
URL = "s3://my-hugo-demo?region=eu-central-1"
