name: CI
on: push

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    # - name: Hugo setup
    #   uses: actions/hugo-action@master
      # TODO: Pass parameters to docker container?

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'

    - name: build
      run: hugo --minify